apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiassistant-ui.fullname" . }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aiassistant-ui.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "aiassistant-ui.fullname" . }}
    spec:
      containers:
      - name: ui
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
