namespace: aiassistant-ui-test
replicaCount: 1
image: sapydi/aiassistant-web:20250827111500-382763a
port: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  cpu: 70

# Add ingress configuration for UI
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "test.aissistant.add-onn.com"  # Main domain for UI
      paths:
        - path: /
          pathType: Prefix
          service: ui-service  # Adjust service name as per your chart
          port: 80
  tls:
    - secretName: aiassistant-add-onn-com-tls
      hosts:
        - aiassistant.add-onn.com